name: lunarestate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2
# for ios
# version: 1.0.0+1
# using diffrent version code bcz android version of this app is +1 version from ios
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.0.2
  bot_toast: ^4.0.3
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.1.0
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  floading: ^2.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_rating_stars: ^1.0.3+4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^1.1.6
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  http: ^0.13.5
  http_parser: ^4.0.2
  image_picker: ^0.8.6
  intl: ^0.19.0
  multi_image_picker_view: ^1.0.2
  page_transition: ^2.0.9
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  provider: ^6.0.4
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sizer: ^2.0.15
  ultimate_bottom_navbar: ^0.0.7
  url_launcher: ^6.3.0
  video_player: ^2.9.1
dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/appIcon.jpg"
# flutter_native_splash:
#   image: "assets/images/tower.jpg"
#   android: true
#   ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/
  fonts:
    - family: RocknRollOne
      fonts:
        - asset: assets/fonts/RocknRollOne-Regular.ttf
    - family: Aspekta
      fonts:
        - asset: assets/fonts/Aspekta-350.ttf
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Medium.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans-BoldItalic.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
        - asset: assets/fonts/PTSans-Italic.ttf
        - asset: assets/fonts/PTSans-Regular.ttf
