class SurveyModel {
  SurveyModel({
    required this.existingMorgage,
    required this.survery,
    required this.washer,
    required this.dryer,
    required this.range,
    required this.gasUtilityavail,
    required this.waterOn,
    required this.sewer,
    required this.backedtaxowed,
    required this.lop,
    required this.isProp,
    required this.lockbox,
    required this.owfinance,
    required this.newhome,
    required this.assitnewhome,
    required this.helpmorgage,
    required this.foundation,
    required this.basement,
    required this.userid,
    required this.tab,
    required this.formid,
  });
  String userid;
  var existingMorgage,
      survery,
      washer,
      dryer,
      range,
      gasUtilityavail,
      waterOn,
      sewer,
      backedtaxowed,
      lop,
      isProp,
      lockbox,
      owfinance,
      newhome,
      assitnewhome,
      helpmorgage,
      foundation,
      tab,
      formid,
      basement;

  // constructor that convert json to object instance
  factory SurveyModel.fromJson(Map<String, dynamic> json) => SurveyModel(
        // survey data
        assitnewhome: json['assitnewhome'],
        backedtaxowed: json['backedtaxowed'],
        basement: json['basement'],
        dryer: json['dryer'],
        existingMorgage: json['existingMorgage'],
        foundation: json['foundation'],
        gasUtilityavail: json['gasUtilityavail'],
        helpmorgage: json['helpmorgage'],
        isProp: json['isProp'],
        lockbox: json['lockbox'],
        lop: json['lop'],
        newhome: json['newhome'],
        owfinance: json['owfinance'],
        range: json['range'],
        sewer: json['sewer'],
        survery: json['survery'],
        washer: json['washer'],
        waterOn: json['waterOn'],
        userid: json['user_id'],
        tab: json['tab'],
        formid: json['formid'],
      );

// a method that convert obj to json String
  Map<String, dynamic> toJson() => {
        // survery data
        'assitnewhome': assitnewhome,
        'backedtaxowed': backedtaxowed,
        'basement': basement,
        'dryer': dryer,
        'existingMorgage': existingMorgage,
        'foundation': foundation,
        'gasUtilityavail': gasUtilityavail,
        'helpmorgage': helpmorgage,
        'isProp': isProp,
        'lockbox': lockbox,
        'lop': lop,
        'newhome': newhome,
        'owfinance': owfinance,
        'range': range,
        'sewer': sewer,
        'survery': survery,
        'washer': washer,
        'waterOn': waterOn,
        'user_id': userid,
        'tab': tab,
        'formid': formid,
      };
}
